namespace Jira.Api.OAuth;

/// <summary>
/// Request token information returned by Jira.
/// </summary>
/// <remarks>
/// Creates a request token containing the response from Jira.
/// </remarks>
/// <param name="authorizeUri">The url to authorize the request token generated by Jira.</param>
/// <param name="oAuthToken">The OAuth request token generated by Jira.</param>
/// <param name="oAuthTokenSecret">The OAuth token secret generated by Jira.</param>
/// <param name="oAuthCallbackConfirmation">The OAuth callback confirmation code.</param>
public class OAuthRequestToken(
	string authorizeUri,
	string oAuthToken,
	string oAuthTokenSecret,
	string oAuthCallbackConfirmation)
{
	/// <summary>
	/// The URL to authorize the request token
	/// </summary>
	public string AuthorizeUri { get; } = authorizeUri;

	/// <summary>
	/// The OAuth request token
	/// </summary>
	public string OAuthToken { get; } = oAuthToken;

	/// <summary>
	/// The OAuth token secret
	/// </summary>
	public string OAuthTokenSecret { get; } = oAuthTokenSecret;

	/// <summary>
	/// The OAuth callback confirmation code
	/// </summary>
	public string OAuthCallbackConfirmation { get; } = oAuthCallbackConfirmation;
}
