namespace Jira.Api.OAuth;

/// <summary>
/// Request token information returned by Jira.
/// </summary>
/// <remarks>
/// Creates a request token containing the response from Jira.
/// </remarks>
/// <param name="authorizeUri">The url to authorize the request token generated by Jira.</param>
/// <param name="oAuthToken">The OAuth request token generated by Jira.</param>
/// <param name="oAuthTokenSecret">The OAuth token secret generated by Jira.</param>
/// <param name="oAuthCallbackConfirmation">The OAuth callback confirmation code.</param>
public class OAuthRequestToken(
	string authorizeUri,
	string oAuthToken,
	string oAuthTokenSecret,
	string oAuthCallbackConfirmation)
{
	/// <summary>
	/// The URL to authorize the request token
	/// </summary>
	public readonly string AuthorizeUri = authorizeUri;

	/// <summary>
	/// The OAuth request token
	/// </summary>
	public readonly string OAuthToken = oAuthToken;

	/// <summary>
	/// The OAuth token secret
	/// </summary>
	public readonly string OAuthTokenSecret = oAuthTokenSecret;

	/// <summary>
	/// The OAuth callback confirmation code
	/// </summary>
	public readonly string OAuthCallbackConfirmation = oAuthCallbackConfirmation;
}
