namespace Jira.Api.OAuth;

/// <summary>
/// Request token information returned by Jira.
/// </summary>
/// <remarks>
/// Creates a request token containing the response from Jira.
/// </remarks>
/// <param name="authorizeUri">The url to authorize the request token generated by Jira.</param>
/// <param name="oAuthToken">The OAuth request token generated by Jira.</param>
/// <param name="oAuthTokenSecret">The OAuth token secret generated by Jira.</param>
public class OAuthRequestToken(
	string authorizeUri,
	string oAuthToken,
	string oAuthTokenSecret,
	string oAuthCallbackConfirmation)
{
	public readonly string AuthorizeUri = authorizeUri;

	public readonly string OAuthToken = oAuthToken;

	public readonly string OAuthTokenSecret = oAuthTokenSecret;

	public readonly string OAuthCallbackConfirmation = oAuthCallbackConfirmation;
}
