using System;

namespace Jira.Api.OAuth;

/// <summary>
/// Access token information returned by Jira.
/// </summary>
/// <remarks>
/// Creates a request token containing the response from Jira.
/// </remarks>
/// <param name="oAuthToken">The OAuth access token generated by Jira.</param>
/// <param name="oAuthTokenSecret">The OAuth token secret generated by Jira.</param>
/// <param name="expiry">The expiry date of the access token.</param>
public class OAuthAccessToken(string oAuthToken, string oAuthTokenSecret, DateTimeOffset oAuthTokenExpiry)
{
	/// <summary>
	/// The OAuth access token generated by Jira.
	/// </summary>
	public readonly string OAuthToken = oAuthToken;

	/// <summary>
	/// The OAuth token secret generated by Jira.
	/// </summary>
	public readonly string OAuthTokenSecret = oAuthTokenSecret;

	/// <summary>
	/// The expiry date of the access token.
	/// </summary>
	public readonly DateTimeOffset OAuthTokenExpiry = oAuthTokenExpiry;
}
